### ISSUE TITLE
analog polling

### ISSUE THREAD

**Issue by builderjer** [MrYsLab/telemetrix-aio#8]
Just a question more than an issue.  Did `analog_read(pin_number)` get removed?  Is there another way to just do polling without a callback?

**Comment by MrYsLab** [comment]
Thanks for the question.
Telemetrix uses callbacks exclusively and does not support polling. This was done to keep the API as simple as possible.

**Comment by builderjer** [comment]
Bummer. Ok thanks for the quick response
